parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  Fusonic\HttpKernelBundle\Controller\RequestDtoResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  App\Core\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: 15 }

  lexik_success_handler:
    class: App\Core\Handler\JwtAuthenticationSuccessHandler

  event.listener:
    class: App\Core\EventListener\Listener
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -1500 }
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 3000 }
